// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO28TQVfMOyveWsngwU3LAC6Gjm-GqvCM',
    appId: '1:55062010989:web:cdcfee4852b42b800bf364',
    messagingSenderId: '55062010989',
    projectId: 'whatsapp2-475bb',
    authDomain: 'whatsapp2-475bb.firebaseapp.com',
    storageBucket: 'whatsapp2-475bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTdgzFy7kMH0P11x9q2JI0uXVfG3He9Hg',
    appId: '1:55062010989:android:b87a88394e3c9e4f0bf364',
    messagingSenderId: '55062010989',
    projectId: 'whatsapp2-475bb',
    storageBucket: 'whatsapp2-475bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGpWrsOC4v-1kfE8rM2A8sbkvTpz2wFk',
    appId: '1:55062010989:ios:f03b5de58790c7530bf364',
    messagingSenderId: '55062010989',
    projectId: 'whatsapp2-475bb',
    storageBucket: 'whatsapp2-475bb.appspot.com',
    iosClientId: '55062010989-r0mjuuphrj34s7qobdjsb8s1tqac74bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
